Repository ConnectingChips/ConnectingChips-Front, pull requests merged in 2023-09, with the labels that each got.

#13 Feat/home welcome
  .gitignore
  package-lock.json
  package.json
  public/_redirects
  src/Component/CTA/CTAContainer.tsx
  src/Hooks/fetchMyList.ts
  src/Hooks/useMission.ts
  src/Page/GroupPage/PostHeader.tsx
  src/Page/Home/Carresel/ButtonList.tsx
  src/Page/Home/Carresel/Carresel.tsx
  src/Page/Home/Carresel/CarreselBarrel.ts
  src/Page/Home/Carresel/CarreselSlideButton.tsx
  src/Page/Home/GroupList.tsx
  src/Page/Home/Home.tsx
  src/Page/Home/HomeBarrel.ts
  src/Page/Home/HomeImageBarrel.ts
  src/Page/Home/MyMisson.tsx
  src/Page/LogIn/LogIn.tsx
  src/StyleComp/ImageBoxS.tsx
  src/Type/ListType.ts
  src/Type/MissionType.ts
  src/data/initialData.ts
  src/data/myInfo.ts
  src/data/postInfoData.ts
  src/data/testData.ts
  src/image/예시사진모음/default_profile_B.svg
  src/image/예시사진모음/default_profile_W.png
Labels: 홈

#16 Feat/home welcome
  src/API/fetchMyList.ts
  src/Component/CTA/CTAContainer.tsx
  src/Hooks/useMission.ts
  src/Page/Home/Carresel/ButtonList.tsx
  src/Page/Home/HomeBarrel.ts
  src/StyleComp/ImageBoxS.tsx
Labels: 홈

#22 🐣 Feat/group intro
  public/noMind.png
  src/Component/CTA/CTAContainer.tsx
  src/Component/Mission/GroupHeader.tsx
  src/Component/Mission/HeadLine.tsx
  src/Component/Mission/MissionIntro.tsx
  src/Component/Mission/MissionRule.tsx
  src/Page/GroupIntro/GroupIntro.tsx
  src/Page/GroupPage/Comment.tsx
  src/Page/GroupPage/GroupActive.tsx
  src/Page/GroupPage/GroupPage.tsx
  src/Page/GroupPage/GroupPageBarrel.ts
  src/Page/GroupPage/PostContent.tsx
  src/Page/GroupPage/PostHeader.tsx
  src/data/postInfoData.ts
Labels: 그룹소개

#24 🐹 Feat/login 로그인, 회원가입 입력폼 수정
  src/Component/SignUp/Banner.tsx
  src/Component/SignUp/Terms.tsx
  src/Component/SignUp/terms_data.ts
  src/Hooks/useSignup.ts
  src/Page/LogIn/LogIn.tsx
  src/Page/SignUp/SignUp.tsx
  src/Page/SignUp/SignUpBarrel.ts
  src/StyleComp/LoginInputS.tsx
Labels: 로그인, 회원가입

#35 🐹 약관 동의 모달 구현
  src/Component/ArrowBarrel.ts
  src/Component/SignUp/Terms.tsx
  src/Component/SignUp/TermsModal.tsx
  src/Component/SignUp/terms_data.ts
  src/StyleComp/GlobalStyle.tsx
  src/image/Icon/close_icon.svg
Labels: 회원가입

#38 🐴 홈 마이페이지 404페이지 디자인 규격 적용
  src/Component/CTA/CTAContainer.tsx
  src/Component/ConfirmModal.tsx
  src/Component/Mission/MissionTab.tsx
  src/Page/Home/Carresel/ButtonList.tsx
  src/Page/Home/GroupList.tsx
  src/Page/Home/Home.tsx
  src/Page/MyPage/MyPage.tsx
  src/Page/MyPage/MyPageMind.tsx
  src/StyleComp/GlobalStyle.tsx
  src/data/groupListData.ts
  src/image/Icon/Info_icon_B.svg
Labels: 홈, 마이페이지

#39 🐴 구글 애널리틱스(GA) 라이브러리 추가 구현
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/Component/ConfirmModal.tsx
  src/Page/MyPage/MyPage.tsx
  src/RouteChangeTracker.ts
  src/index.tsx
Labels: 공통

#42 🐣 그룹페이지 : 리팩토링
  src/Page/GroupIntro/ActiveExample.tsx
  src/Page/GroupPage/Comment.tsx
  src/Page/GroupPage/CommentHeader.tsx
  src/Page/GroupPage/CommentInput.tsx
  src/Page/GroupPage/CommentList.tsx
  src/Page/GroupPage/GroupPage.tsx
  src/Page/GroupPage/GroupPageBarrel.ts
  src/Page/Home/Home.tsx
  src/data/postInfoData.ts
Labels: 그룹소개

#43 ✨ Feat : axios api 추가
  package-lock.json
  package.json
  src/API/axiosConfig.ts
  src/API/joindMinds.ts
  src/API/userMind.ts
  src/API/userService.ts
  src/Page/Home/Home.tsx
Labels: 홈, 공통

#45 인증하기 UI 작업
  src/Component/Mission/GroupArticle.tsx
  src/Component/Mission/GroupHeader.tsx
  src/Component/Mission/MissionRule.tsx
  src/Component/UploadPost/InfoMessage.tsx
  src/Page/GroupIntro/ActiveExample.tsx
  src/Page/Home/Home.tsx
  src/Page/UploadPost/UploadPost.tsx
  src/image/Icon/add_icon.svg
  src/image/Icon/close_icon_light_gray.svg
  src/image/Icon/delete_icon.svg
  src/image/Icon/image_input_icon.png
Labels: 인증 글쓰기

#46 AXIOS 요청 로직 / 네트워크 통신 테스트
  src/API/axiosConfig.ts
  src/API/fetchMyList.ts
  src/API/joinedMinds.ts
  src/API/logText.ts
  src/API/userMind.ts
  src/API/userService.ts
  src/Component/ArticleTab.tsx
  src/Component/ConfirmModal.tsx
  src/Component/OAuthPage.tsx
  src/Page/GroupPage/CommentList.tsx
  src/Page/Home/Carresel/ButtonList.tsx
  src/Page/Home/Carresel/Carresel.tsx
  src/Page/Home/Carresel/useCarresel.ts
  src/Page/Home/GroupList.tsx
  src/Page/Home/Home.tsx
  src/Page/Home/HomeBarrel.ts
  src/Page/Home/MyMisson.tsx
  src/Page/LogIn/LogIn.tsx
  src/Page/MyPage/MyPage.tsx
  src/Page/MyPage/MyPageMind.tsx
  src/Page/MyPage/MypageBarrel.ts
  src/Page/SignUp/SignUp.tsx
  src/Type/ListType.ts
  src/Type/MissionType.ts
  src/Type/User.ts
  src/Type/userMind.ts
  src/data/groupListData.ts
  src/data/initialData.ts
  src/data/myInfo.ts
Labels: 홈, 로그인, 마이페이지, 공통, API

#47 🐣 : Boards, Comment, Reply api 연결
  src/API/Boards.ts
  src/API/Comment.ts
Labels: API

#53 🔨 Refactor : Props 2단계 제거 / 요청 분할
  src/API/Boards.ts
  src/API/Comment.ts
  src/API/Context.ts
  src/API/axiosConfig.ts
  src/API/joinedMinds.ts
  src/API/logText.ts
  src/API/userMind.ts
  src/API/userService.ts
  src/App.tsx
  src/Component/ConfirmModal.tsx
  src/Component/Mission/GroupArticle.tsx
  src/Component/Mission/GroupContent.tsx
  src/Component/Mission/GroupHeader.tsx
  src/Component/Mission/HeadLine.tsx
  src/Hooks/useFindGroup.ts
  src/Hooks/useMyContext.ts
  src/Page/GroupIntro/GroupIntro.tsx
  src/Page/GroupPage/GroupPage.tsx
  src/Page/Home/GroupList.tsx
  src/Page/Home/Home.tsx
  src/Page/Home/HomeBarrel.ts
  src/Page/Home/MyMisson.tsx
  src/Page/LogIn/LogIn.tsx
  src/Page/MyPage/MyPage.tsx
  src/Page/MyPage/MyPageMind.tsx
  src/Page/MyPage/MypageBarrel.ts
  src/Page/SignUp/SignUp.tsx
  src/Page/UploadPost/UploadPost.tsx
  src/Type/ListType.ts
  src/Type/User.ts
  src/Type/userMind.ts
  src/data/initialData.ts
  src/data/missionTab.ts
  src/data/myInfo.ts
Labels: 그룹소개, 그룹페이지, 로그인

#54 🐣 api연결을 위한 파일정리
  public/defalutProfileImage.jpg
  src/API/Boards.ts
  src/API/Comment.ts
  src/API/userMind.ts
  src/API/userService.ts
  src/Page/GroupPage/Comment.tsx
  src/Page/GroupPage/CommentHeader.tsx
  src/Page/GroupPage/CommentList.tsx
  src/Page/GroupPage/GroupActive.tsx
  src/Page/GroupPage/GroupPage.tsx
  src/Page/GroupPage/GroupPageBarrel.ts
  src/Page/GroupPage/GroupPost.tsx
  src/Page/GroupPage/GroupPostList.tsx
  src/Page/GroupPage/PostContent.tsx
  src/Page/GroupPage/PostHeader.tsx
Labels: 공통, API

#57 로그인, 회원가입, 글쓰기 api 구현 및 연결
  src/API/Boards.ts
  src/API/axiosConfig.ts
  src/API/login.ts
  src/API/signup.ts
  src/Page/LogIn/LogIn.tsx
  src/Page/SignUp/SignUp.tsx
  src/Page/UploadPost/UploadPost.tsx
Labels: 인증 글쓰기, 로그인, 회원가입

#56 Feat/group api2
  src/API/Boards.ts
  src/API/Comment.ts
  src/API/fetchMyList.ts
  src/API/userMind.ts
  src/API/userService.ts
  src/Component/CTA/CTAContainer.tsx
  src/Component/Mission/GroupArticle.tsx
  src/Component/Mission/HeadLine.tsx
  src/Component/Mission/MissionIntro.tsx
  src/Component/Mission/MissionRule.tsx
  src/Hooks/useMission.ts
  src/Page/GroupPage/Comment.tsx
  src/Page/GroupPage/CommentInput.tsx
  src/Page/GroupPage/CommentList.tsx
  src/Page/GroupPage/GroupPage.tsx
  src/Page/GroupPage/GroupPost.tsx
  src/Page/GroupPage/GroupPostList.tsx
  src/Page/GroupPage/PostContent.tsx
  src/Page/GroupPage/PostHeader.tsx
  src/Page/MyPage/MyPageMind.tsx
  src/Page/MyPage/MypageBarrel.ts
  src/Type/Group.ts
Labels: 그룹소개, 그룹페이지, 공통

#55 ✨ Feat : 전역 상태(myInfo, myList) / 실제 API 적용 / 토큰 데이터화
  src/API/Boards.ts
  src/API/Comment.ts
  src/API/Context.ts
  src/API/Users.ts
  src/API/joinedMinds.ts
  src/API/logText.ts
  src/API/userMind.ts
  src/App.tsx
  src/Component/ArticleTab.tsx
  src/Component/CTA/CTAContainer.tsx
  src/Component/GroupCheck.tsx
  src/Component/Mission/GroupArticle.tsx
  src/Component/Mission/MissionTab.tsx
  src/Component/OAuthPage.tsx
  src/Hooks/useFindGroup.ts
  src/Page/GroupIntro/GroupIntro.tsx
  src/Page/GroupPage/GroupPageBarrel.ts
  src/Page/Home/Carresel/ButtonList.tsx
  src/Page/Home/Carresel/Carresel.tsx
  src/Page/Home/Carresel/CarreselBarrel.ts
  src/Page/Home/GroupList.tsx
  src/Page/Home/Home.tsx
  src/Page/Home/HomeBarrel.ts
  src/Page/Home/MyMisson.tsx
  src/Page/MyPage/MyPage.tsx
  src/Page/MyPage/MyPageMind.tsx
  src/Page/MyPage/MypageBarrel.ts
  src/Page/SignUp/SignUp.tsx
  src/Page/UploadPost/UploadPost.tsx
  src/Type/Group.ts
  src/Type/userMind.ts
  src/data/CoverBarrel.tsx
  src/data/groupListData.ts
  src/data/initialData.ts
  src/data/myInfo.ts
  src/data/postInfoData.ts
  src/data/tocken.ts
Labels: 홈, 마이페이지, 공통

#59 에러 수정, 코드 정리
  src/API/axiosConfig.ts
  src/API/userMind.ts
  src/Page/SignUp/SignUp.tsx
  src/Page/UploadPost/UploadPost.tsx
Labels: 인증 글쓰기, 로그인, 회원가입, 공통

#60 🔨 Refactor : 파일명 폴더명 정리
  src/API/Context.ts
  src/API/Mind.ts
  src/API/joinedMinds.ts
  src/API/logText.ts
  src/Component/Mission/GroupArticle.tsx
  src/Component/Mission/HeadLine.tsx
  src/Component/Mission/MissionRule.tsx
  src/Hooks/useMyContext.ts
  src/Page/GroupPage/GroupPage.tsx
  src/Page/GroupPage/GroupPostList.tsx
  src/Page/Home/Carresel/ButtonList.tsx
  src/Page/Home/Carresel/Carresel.tsx
  src/Page/Home/Carresel/useCarresel.ts
  src/Page/Home/GroupList.tsx
  src/Page/Home/Home.tsx
  src/Page/Home/HomeBarrel.ts
  src/Page/Home/MyMisson.tsx
  src/Page/MyPage/MyPageMind.tsx
  src/Page/MyPage/MypageBarrel.ts
  src/Page/UploadPost/UploadPost.tsx
  src/Type/Board.ts
  src/Type/Group.ts
  src/Type/Mind.ts
  src/Type/userMind.ts
  src/data/initialData.ts
Labels: 홈, 마이페이지, 공통

#61 💬 Comment : mindID -> mindId로 변경
  src/App.tsx
  src/Component/CTA/CTAContainer.tsx
  src/Component/Mission/GroupArticle.tsx
  src/Component/Mission/MissionIntro.tsx
  src/Page/GroupPage/GroupPage.tsx
  src/Page/GroupPage/GroupPostList.tsx
  src/Page/GroupPage/PostContent.tsx
  src/Page/UploadPost/UploadPost.tsx
Labels: 공통

#62 🔨 Refactor : mindID 이름 변경
  src/Component/GroupCheck.tsx
Labels: 공통

#63 GroupHeader params -> mindId로 변경
  src/Component/Mission/GroupHeader.tsx
Labels: 공통

#65 ⚠ Fix : Home -> MyPage -> Login 구현중
  src/API/Users.ts
  src/API/joinedMinds.ts
  src/Component/ConfirmModal.tsx
  src/Component/OAuthPage.tsx
  src/Page/Home/Carresel/ButtonList.tsx
  src/Page/Home/GroupList.tsx
  src/Page/Home/Home.tsx
  src/Page/MyPage/MyPage.tsx
  src/data/tocken.ts
Labels: 홈, 마이페이지

#67 ⚠ Fix : MindTypeId 수정
  src/API/Mind.ts
  src/API/Users.ts
  src/API/joinedMinds.ts
  src/Component/GroupCheck.tsx
Labels: 홈

#68 🐣 groupintro에서 참가하기 api연결
  src/API/axiosConfig.ts
  src/API/joinedMinds.ts
  src/Component/CTA/CTAContainer.tsx
  src/Page/GroupPage/GroupPage.tsx
  src/Page/GroupPage/PostHeader.tsx
Labels: 그룹소개

#69 글쓰기 api 마무리, 에러 핸들링
  src/API/Boards.ts
  src/API/axiosConfig.ts
  src/Page/UploadPost/UploadPost.tsx
Labels: 인증 글쓰기

#70 ✨ Feat : 토큰 만료됐을때 로컬스토리지에 있는 토큰 삭제
  src/Page/UploadPost/UploadPost.tsx
Labels: 인증 글쓰기

#71 홈/로그인/마이페이지 이동간 상태 동기화 & Group Check 인증 추가
  src/API/Boards.ts
  src/API/Mind.ts
  src/API/Users.ts
  src/API/axiosConfig.ts
  src/API/joinedMinds.ts
  src/App.tsx
  src/Component/CTA/CTAContainer.tsx
  src/Component/ConfirmModal.tsx
  src/Component/GroupCheck.tsx
  src/Page/Home/Carresel/ButtonList.tsx
  src/Page/Home/GroupList.tsx
  src/Page/Home/Home.tsx
  src/Page/MyPage/MyPage.tsx
  src/Page/MyPage/MyPageMind.tsx
  src/Type/Mind.ts
  src/data/tocken.ts
Labels: 홈, 마이페이지, 공통

#72 이용 약관 추가
  package-lock.json
  package.json
  src/Component/SignUp/Markdown.tsx
  src/Component/SignUp/Terms.tsx
  src/Component/SignUp/TermsModal.tsx
  src/Component/SignUp/terms_data.ts
Labels: 회원가입

#73 로그인, 회원가입 스타일 수정
  src/Component/SignUp/Loginheader.tsx
  src/StyleComp/LoginInputS.tsx
Labels: 로그인, 회원가입

#75 ⚠ Fix : API 버그 수정
  src/API/Boards.ts
  src/API/Mind.ts
Labels: 공통

#76 UI 버그 수정, 약관 데이터 이동
  src/Component/SignUp/Terms.tsx
  src/Component/SignUp/TermsModal.tsx
  src/data/termsPolicyData.ts
Labels: 회원가입

#77 글쓰기 페이지: 유효하지 않은 토큰인 경우 처리
  src/Page/UploadPost/UploadPost.tsx
Labels: 인증 글쓰기

#82 ✨ Feat : OAuthPage / 이용약관 / 이미지 해상도 / 참여했던 작심 반환
  public/Chips_signout.png
  public/oneChip.png
  src/API/Mind.ts
  src/API/axiosConfig.ts
  src/API/joinedMinds.ts
  src/Component/ArticleTab.tsx
  src/Component/ConfirmModal.tsx
  src/Component/OAuthPage.tsx
  src/Page/Home/Home.tsx
  src/Page/MyPage/MyPage.tsx
  src/Page/MyPage/MyPageMind.tsx
  src/Page/MyPage/MypageBarrel.ts
  src/Page/MyPage/TermsModal.tsx
  src/Type/Mind.ts
  src/data/initialData.ts
Labels: 홈, 마이페이지

#78 🐣 그룹페이지 헤더 이미지 추가
  src/Component/Mission/GroupHeader.tsx
  src/Component/Mission/HeadLine.tsx
  src/Page/GroupPage/GroupPage.tsx
  src/Page/GroupPage/GroupPost.tsx
  src/image/Icon/post_Icon_locked.svg
Labels: 그룹페이지

#84 Fix : 글쓰기 페이지 제목 아래에 간격 추가
  src/Component/Mission/HeadLine.tsx
Labels: 인증 글쓰기

#85 ⚠ Fix : QA 전 FIX
  src/API/Mind.ts
  src/API/axiosConfig.ts
  src/API/joinedMinds.ts
  src/Component/ArticleTab.tsx
  src/Component/ConfirmModal.tsx
  src/Component/GroupCheck.tsx
  src/Hooks/useMission.ts
  src/Page/GroupPage/GroupBtn.tsx
  src/Page/Home/Carresel/ButtonList.tsx
  src/Page/Home/Carresel/ChipList.tsx
  src/Page/MyPage/MyPage.tsx
  src/Page/MyPage/MyPageMind.tsx
  src/Type/Mind.ts
Labels: 마이페이지, 공통

#88 이미지 파일 10mb 제한, 토스트 메시지 추가
  package-lock.json
  package.json
  src/Component/CTA/CTAContainer.tsx
  src/Component/Toast/ImgSizeLimitMsg.tsx
  src/Component/Toast/StyledToastContainer.tsx
  src/Page/UploadPost/UploadPost.tsx
  src/Type/custom.d.ts
  src/image/error_Icon.png
Labels: 인증 글쓰기

#87 🔨 Refactor : 타입, 컴포넌트 정리
  src/API/Boards.ts
  src/API/Mind.ts
  src/API/Users.ts
  src/API/joinedMinds.ts
  src/Component/GroupCheck.tsx
  src/Hooks/useMission.ts
  src/Page/Home/Carresel/ButtonList.tsx
  src/Page/Home/Carresel/Carresel.tsx
  src/Page/Home/GroupList.tsx
  src/Page/Home/Home.tsx
  src/Page/Home/MyMisson.tsx
  src/StyleComp/ImageBoxS.tsx
  src/Type/MissionType.ts
Labels: 홈

#90 🔨 Refactor : 최적화 및 코드수 줄이기
  src/Component/Mission/DivideBa.tsx
  src/Page/GroupPage/Comment.tsx
  src/Page/GroupPage/CommentInput.tsx
  src/Page/GroupPage/CommentList.tsx
  src/Page/GroupPage/GroupBtn.tsx
  src/Page/GroupPage/GroupPage.tsx
  src/Page/GroupPage/GroupPost.tsx
  src/Page/GroupPage/GroupPostList.tsx
  src/Page/GroupPage/PostContent.tsx
  src/Page/GroupPage/PostHeader.tsx
Labels: 그룹소개, 그룹페이지

#91 ⚠ Fix : 라우팅, 오타 수정
  src/Component/GroupCheck.tsx
  src/Component/OAuthPage.tsx
  src/Page/Home/Carresel/Carresel.tsx
Labels: 홈, 공통

#92 🐣 : 참여하기 에러, intro 간격 에러 해결
  src/API/joinedMinds.ts
  src/Page/GroupIntro/GroupIntro.tsx
Labels: 그룹소개, 그룹페이지

#93 🔨 Refactor : 전체 작심 마이페이지 문구 및 스타일 수정
  src/API/joinedMinds.ts
  src/Component/ConfirmModal.tsx
  src/Page/Home/Carresel/ButtonList.tsx
  src/Page/Home/Carresel/Carresel.tsx
  src/Page/Home/GroupList.tsx
  src/Page/Home/Home.tsx
  src/Page/MyPage/MyPage.tsx
  src/Page/MyPage/MyPageMind.tsx
  src/Type/Mind.ts
Labels: 홈

#94 1차 QA 수정사항
  src/API/Boards.ts
  src/API/Comment.ts
  src/API/joinedMinds.ts
  src/Component/CTA/CTAContainer.tsx
  src/Component/Mission/GroupHeader.tsx
  src/Page/GroupIntro/GroupIntro.tsx
  src/Page/GroupPage/Comment.tsx
  src/Page/GroupPage/CommentInput.tsx
  src/Page/GroupPage/CommentList.tsx
  src/Page/GroupPage/GroupBtn.tsx
Labels: 그룹소개, 그룹페이지

#95 QA 후 변경사항 수정
  src/Component/SignUp/Terms.tsx
  src/Hooks/scrollTopSmooth.ts
  src/Page/LogIn/LogIn.tsx
  src/Page/SignUp/SignUp.tsx
  src/Page/UploadPost/UploadPost.tsx
  src/StyleComp/LoginInputS.tsx
  src/StyleComp/SignBtnS.tsx
Labels: 인증 글쓰기, 로그인, 회원가입

#97 ⚠ Fix : Intro 페이지 GroupCheck / 인증하기 버튼 글자
  src/App.tsx
  src/Component/GroupCheck.tsx
  src/Page/Home/Carresel/ButtonList.tsx
  src/Page/Home/Home.tsx
Labels: 홈, 공통

#98 [Fix/modal] 모달 연 상태에서 뒤로가기 시 모든 페이지 스크롤 안되는 문제 해결
  src/Component/SignUp/TermsModal.tsx
Labels: 회원가입

#100 작심 별 다른 예시 이미지 적용
  src/API/Mind.ts
  src/Page/GroupIntro/ActiveExample.tsx
Labels: 인증 글쓰기

#102 ⚠ Fix : 그룹 페이지 버튼 상태 수정
  src/API/Mind.ts
  src/Component/Mission/GroupArticle.tsx
  src/Component/Mission/GroupHeader.tsx
  src/Page/GroupPage/GroupBtn.tsx
  src/Page/Home/Home.tsx
Labels: 그룹페이지

#103 [Fix/image] 이미지 확장자 제한
  src/Page/UploadPost/UploadPost.tsx
Labels: 인증 글쓰기

#110 QA 3차 수정본[용주]
  src/Component/CTA/CTAContainer.tsx
  src/Component/ConfirmModal.tsx
  src/Component/Mission/DivideBa.tsx
  src/Component/Mission/GroupArticle.tsx
  src/Component/Mission/GroupContent.tsx
  src/Component/Mission/GroupHeader.tsx
  src/Component/Mission/MissionRule.tsx
  src/Component/Mission/MissionTab.tsx
  src/Page/GroupIntro/GroupIntro.tsx
  src/Page/GroupPage/CommentInput.tsx
  src/Page/GroupPage/GroupBtn.tsx
  src/Page/GroupPage/GroupPage.tsx
  src/Page/GroupPage/GroupPostList.tsx
  src/Page/GroupPage/PostContent.tsx
Labels: 그룹소개, 그룹페이지

#115 QA 수정사항 4차
  src/API/Mind.ts
  src/API/joinedMinds.ts
  src/App.tsx
  src/Component/CTA/CTAContainer.tsx
  src/Component/GroupCheck.tsx
  src/Component/Mission/GroupArticle.tsx
  src/Component/Mission/MissionRule.tsx
  src/Component/Mission/MissionTab.tsx
  src/Page/GroupIntro/GroupIntro.tsx
  src/Page/GroupPage/Comment.tsx
  src/Page/GroupPage/GroupPage.tsx
  src/Page/GroupPage/GroupPost.tsx
  src/Page/GroupPage/GroupPostList.tsx
  src/Page/GroupPage/PostContent.tsx
  src/StyleComp/GlobalStyle.tsx
Labels: 그룹소개, 그룹페이지

#122 [Fix] 중복된 html meta description 삭제
  public/index.html
Labels: 공통

#124 [Feat] GTM 코드 추가
  public/index.html
Labels: 공통

#125 작심삼칩 v1.0.1
  public/index.html
Labels: 공통
