Repository ConnectingChips/ConnectingChips-Front, pull requests merged in 2023-10, with the labels that each got.

#129 🔨 Refactor : 리팩토링
  src/API/Boards.ts
  src/API/Comment.ts
  src/API/Mind.ts
  src/API/Users.ts
  src/API/joinedMinds.ts
  src/App.tsx
  src/AppBarral.ts
  src/Component/GroupCheck.tsx
  src/Component/Mission/GroupArticle.tsx
  src/Component/Mission/GroupContent.tsx
  src/Component/Mission/HeadLine.tsx
  src/Component/Mission/MissionIntro.tsx
  src/Component/Mission/MissionRule.tsx
  src/Component/Mission/MissionTab.tsx
  src/Component/SignUp/Loginheader.tsx
  src/Component/SignUp/Terms.tsx
  src/Page/GroupIntro/ActiveExample.tsx
  src/Page/GroupPage/GroupPageBarrel.ts
  src/Page/GroupPage/GroupPost.tsx
  src/Page/GroupPage/PostHeader.tsx
  src/Page/Home/Carresel/ButtonList.tsx
  src/Page/Home/Carresel/Carresel.tsx
  src/Page/Home/GroupList.tsx
  src/Page/Home/Home.tsx
  src/Page/Home/HomeBarrel.ts
  src/Page/Home/HomeImageBarrel.ts
  src/Page/Home/MyMisson.tsx
  src/Page/Home/SampleImage.ts
  src/Page/MyPage/MyPage.tsx
  src/Page/MyPage/MypageBarrel.ts
  src/Page/UploadPost/UploadPost.tsx
  src/StyleComp/GlobalStyle.tsx
  src/StyleComp/SignBtnS.tsx
  src/Type/Board.ts
  src/Type/LikeBind.ts
  src/Type/Mind.ts
  src/Type/MissionType.ts
  src/Type/PostInfo.ts
  src/data/initialData.ts
  src/data/missionTab.ts
  src/data/tocken.ts
  src/index.tsx
  tsconfig.json
Labels: 공통

#136 🔨 Refactor : 마이페이지 리팩토링
  src/Component/ArticleTab.tsx
  src/Component/ConfirmModal.tsx
  src/Page/Home/Home.tsx
  src/Page/MyPage/MyPage.tsx
  src/Page/MyPage/MyPageMind.tsx
  src/Page/MyPage/MypageBarrel.ts
Labels: 마이페이지

#137 🔨 Refactor : 작심 인트로 리팩토링
  src/API/Mind.ts
  src/Component/CTA/CTAContainer.tsx
  src/Component/Mission/DivideBa.tsx
  src/Component/Mission/GroupArticle.tsx
  src/Component/Mission/GroupContent.tsx
  src/Component/Mission/GroupHeader.tsx
  src/Component/Mission/HeadLine.tsx
  src/Component/Mission/MissionIntro.tsx
  src/Component/Mission/MissionRule.tsx
  src/Component/Mission/MissionTab.tsx
  src/Page/GroupIntro/ActiveExample.tsx
  src/Page/GroupIntro/GroupIntro.tsx
  src/Page/GroupIntro/IntroBarrel.ts
  src/Page/GroupPage/GroupPage.tsx
  src/Page/GroupPage/GroupPageBarrel.ts
  src/Page/NotFound/NotFound.tsx
  src/Page/UploadPost/UploadPost.tsx
  src/StyleComp/GlobalStyle.tsx
  src/StyleComp/SignBtnS.tsx
Labels: 그룹소개, 그룹페이지, 회원가입, 공통

#144 JSSC-91/GTM/Home
  src/Page/Home/Carresel/Carresel.tsx
Labels: 홈

#143 Jssc 75/refactor/mind page
  package-lock.json
  package.json
  src/App.tsx
  src/Component/CTA/CTAContainer.tsx
  src/Component/DeleteModal.tsx
  src/Component/Mission/GroupArticle.tsx
  src/Component/Mission/GroupHeader.tsx
  src/Component/Mission/MissionTab.tsx
  src/Component/SignUp/Loginheader.tsx
  src/Page/GroupIntro/GroupIntro.tsx
  src/Page/GroupPage/Comment/Comment.tsx
  src/Page/GroupPage/Comment/CommentBarrel.ts
  src/Page/GroupPage/Comment/CommentHeader.tsx
  src/Page/GroupPage/Comment/CommentInput.tsx
  src/Page/GroupPage/Comment/CommentList.tsx
  src/Page/GroupPage/CommentList.tsx
  src/Page/GroupPage/GroupBtn.tsx
  src/Page/GroupPage/GroupPage.tsx
  src/Page/GroupPage/GroupPageBarrel.ts
  src/Page/GroupPage/GroupPost.tsx
  src/Page/GroupPage/GroupPostList.tsx
  src/Page/GroupPage/Post/GroupPost.tsx
  src/Page/GroupPage/Post/GroupPostList.tsx
  src/Page/GroupPage/Post/PostBarrel.ts
  src/Page/GroupPage/Post/PostContent.tsx
  src/Page/GroupPage/PostHeader.tsx
  src/Page/GroupPage/PostPropsType.ts
  src/Page/Home/Carresel/Carresel.tsx
  src/Page/Home/Carresel/CarreselBarrel.ts
  src/Page/MyPage/MyPage.tsx
  src/Page/UploadPost/UploadPost.tsx
  src/StyleComp/GlobalStyle.tsx
  src/data/initialData.ts
Labels: 홈, 그룹페이지, 회원가입

#145 Jssc 89 작심하기, 재작심하기 버튼
  src/API/joinedMinds.ts
  src/Page/GroupPage/GroupBtn.tsx
  src/Page/Home/Carresel/ButtonList.tsx
  src/Page/Home/Home.tsx
  src/Type/Mind.ts
Labels: 홈, 그룹페이지

#146 JSSC-75/Barrel 방식
  src/Component/DeleteModal.tsx
  src/Page/GroupPage/Comment/Comment.tsx
  src/Page/GroupPage/Comment/CommentBarrel.ts
  src/Page/GroupPage/Comment/CommentHeader.tsx
  src/Page/GroupPage/Comment/CommentInput.tsx
  src/Page/GroupPage/Comment/CommentList.tsx
  src/Page/GroupPage/GroupPageBarrel.ts
  src/Page/GroupPage/Post/GroupPost.tsx
  src/Page/GroupPage/Post/GroupPostList.tsx
  src/Page/GroupPage/Post/PostBarrel.ts
  src/Page/GroupPage/Post/PostContent.tsx
  src/Page/GroupPage/Post/PostListBarrel.ts
  src/Page/GroupPage/PostHeader.tsx
  src/Type/Bind.ts
Labels: 그룹페이지

#148 [JSSC-67] 인증하기 페이지 1차 리팩토링
  src/Component/UploadPost/UploadImage.tsx
  src/Component/UploadPost/UploadImageTitle.tsx
  src/Component/UploadPost/UploadPostHeader.tsx
  src/Component/UploadPost/UploadText.tsx
  src/Page/UploadPost/UploadPost.tsx
  src/StyleComp/UploadWrapperS.tsx
Labels: 인증 글쓰기

#149 [JSSC-112] 이미지 필수 선택 기능 추가
  src/Component/CTA/CTAContainer.tsx
  src/Component/UploadPost/UploadImageTitle.tsx
  src/Page/UploadPost/UploadPost.tsx
Labels: 인증 글쓰기

#151 [JSSC1231] 🎨 Style: 홈 반응형 디자인 (최소 320px 대응)
  src/Component/Mission/MissionTab.tsx
  src/Page/Home/GroupList.tsx
  src/Page/Home/Home.tsx
Labels: 홈

#150 Jssc 66 groupPage 리팩토링
  src/API/Boards.ts
  src/Component/DeleteModal.tsx
  src/Component/Mission/GroupHeader.tsx
  src/Component/UploadPost/CreateExample.tsx
  src/Component/UploadPost/UploadPostHeader.tsx
  src/Page/GroupIntro/IntroBarrel.ts
  src/Page/GroupPage/Comment/Comment.tsx
  src/Page/GroupPage/Comment/CommentInput.tsx
  src/Page/GroupPage/Comment/CommentList.tsx
  src/Page/GroupPage/Comment/CommentToolbar.tsx
  src/Page/GroupPage/GroupPage.tsx
  src/Page/GroupPage/GroupPageBarrel.ts
  src/Page/GroupPage/Post/GroupPost.tsx
  src/Page/GroupPage/Post/GroupPostList.tsx
  src/Page/GroupPage/Post/PostContent.tsx
  src/Page/GroupPage/Post/PostHeader.tsx
  src/Page/GroupPage/Post/PostListBarrel.ts
  src/Page/GroupPage/PostHeader.tsx
  src/Page/UploadPost/UploadPost.tsx
Labels: 그룹소개, 그룹페이지

#153 [JSSC-138] 이미지 누락 에러 핸들링
  src/API/Boards.ts
  src/API/Mind.ts
  src/Page/UploadPost/UploadPost.tsx
  src/constant/error.ts
Labels: 인증 글쓰기

#152 [JSSC-140] 🎨 Style: 마이페이지 반응형 디자인 (최소 320px) / 이용약관 추가
  src/Component/ArticleTab.tsx
  src/Page/MyPage/MyPage.tsx
  src/Page/MyPage/MyPageMind.tsx
  src/Page/MyPage/TermsModal.tsx
  src/StyleComp/GlobalStyle.tsx
  src/Type/TermsValue.ts
Labels: 마이페이지

#154 [Jssc 140] ⚠ Fix: 홈 및 마이페이지 레이아웃 수정
  src/Component/Mission/MissionTab.tsx
  src/Page/GroupIntro/GroupIntro.tsx
  src/Page/MyPage/MyPage.tsx
  src/Page/MyPage/MyPageMind.tsx
Labels: 홈, 마이페이지

#155 [JSSC-140] ⚠ Fix: 전체 작심 현황 보더
  src/Component/Mission/MissionTab.tsx
Labels: 마이페이지

#160 [JSSC-152] 아이디 중복확인 버튼 추가
  src/Component/SignUp/SquareButton.tsx
  src/Component/UploadPost/UploadImageTitle.tsx
  src/Hooks/scrollTopSmooth.ts
  src/Page/SignUp/SignUp.tsx
  src/StyleComp/LoginInputS.tsx
  src/image/Icon/check-icon.svg
Labels: 회원가입

#161 [JSSC-140] Home 및 마이페이지 스타일 수정
  src/Page/Home/Home.tsx
  src/Page/MyPage/MyPage.tsx
Labels: 마이페이지

#164 댓글페이지 리팩토링 및 버그수정
  src/Component/ArrowBarrel.ts
  src/Component/DeleteModal.tsx
  src/Component/Markdown/Markdown.tsx
  src/Component/Mission/GroupHeader.tsx
  src/Component/SignUp/Banner.tsx
  src/Component/SignUp/TermsModal.tsx
  src/Component/UploadPost/UploadPostHeader.tsx
  src/Page/GroupIntro/GroupIntro.tsx
  src/Page/GroupIntro/IntroBarrel.ts
  src/Page/GroupPage/Comment/Comment.tsx
  src/Page/GroupPage/Comment/CommentInput.tsx
  src/Page/GroupPage/Comment/CommentPage.tsx
  src/Page/GroupPage/Comment/CommentToolbar.tsx
  src/Page/GroupPage/GroupBtn.tsx
  src/Page/GroupPage/GroupPage.tsx
  src/Page/GroupPage/GroupPageBarrel.ts
  src/Page/GroupPage/Post/GroupPost.tsx
  src/Page/GroupPage/Post/GroupPostList.tsx
  src/Page/GroupPage/Post/PostContent.tsx
  src/Page/GroupPage/Post/PostHeader.tsx
  src/Page/GroupPage/Post/PostListBarrel.ts
  src/Page/LogIn/LogIn.tsx
  src/Page/MyPage/MyPage.tsx
  src/Page/MyPage/TermsModal.tsx
  src/Page/SignUp/SignUp.tsx
  src/Page/UploadPost/UploadPost.tsx
  src/StyleComp/LoginInputS.tsx
Labels: 그룹페이지, 공통

#165 [J SSC-36] 메일 인증 기능 추가
  src/API/Users.ts
  src/Component/SignUp/EmailVerificationContents.tsx
  src/Component/SignUp/EmailVerificationMessage.tsx
  src/Component/SignUp/EmailVerificationModal.tsx
  src/Component/SignUp/TermsModal.tsx
  src/Component/Toast/EmailErrorMsg.tsx
  src/Page/SignUp/SignUp.tsx
  src/constant/error.ts
  src/image/exclamation-mark-chips.png
Labels: 회원가입
